[package]
name = "bluebird"
version = "0.1.1"
authors = ["Dan Rammer <hamersaw@gmail.com>"]

[dependencies]
hyper = "*"
rand = "*"
rust-crypto = "*"
rustc-serialize = "*"
time = "*"

[[example]]
name = "filter_stream"
path = "examples/filter_stream/filter_stream.rs"
